// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjZzJhvBoLvLIZ3FUxoweY86aGnvMyPU',
    appId: '1:338801247904:web:e313da513248fb6f2aabc5',
    messagingSenderId: '338801247904',
    projectId: 'food-quardian',
    authDomain: 'food-quardian.firebaseapp.com',
    storageBucket: 'food-quardian.firebasestorage.app',
    measurementId: 'G-C392Y5PFZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwilpOog8ABD6fu5nEl5V2yHDXx7_Bm3Q',
    appId: '1:338801247904:android:bd7003e0c3542d962aabc5',
    messagingSenderId: '338801247904',
    projectId: 'food-quardian',
    storageBucket: 'food-quardian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVEOXh7utGegooJn55BbUgoznOuDBTRw',
    appId: '1:338801247904:ios:21e12da4770e8df62aabc5',
    messagingSenderId: '338801247904',
    projectId: 'food-quardian',
    storageBucket: 'food-quardian.firebasestorage.app',
    iosBundleId: 'com.example.foodGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVEOXh7utGegooJn55BbUgoznOuDBTRw',
    appId: '1:338801247904:ios:21e12da4770e8df62aabc5',
    messagingSenderId: '338801247904',
    projectId: 'food-quardian',
    storageBucket: 'food-quardian.firebasestorage.app',
    iosBundleId: 'com.example.foodGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdjZzJhvBoLvLIZ3FUxoweY86aGnvMyPU',
    appId: '1:338801247904:web:ba5291b5d1064c0d2aabc5',
    messagingSenderId: '338801247904',
    projectId: 'food-quardian',
    authDomain: 'food-quardian.firebaseapp.com',
    storageBucket: 'food-quardian.firebasestorage.app',
    measurementId: 'G-819LVPBHVE',
  );
}
